name: jambapp
description: Custom project

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.2
  intl: ^0.18.1
  flutter_native_splash: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  color: "#ffc876" # Replace with your background color
  image: assets/images/splash_screen.png
  android: true
  ios: true
  android_gravity: center # Centers the image for Android
  ios_content_mode: center # Centers the image for iOS


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/dice.png
    - assets/images/dice1.png
    - assets/images/dice2.png
    - assets/images/dice3.png
    - assets/images/dice4.png
    - assets/images/dice5.png
    - assets/images/dice6.png
    - assets/images/downarrow.png
    - assets/images/uparrow.png
    - assets/images/updownarrow.png
    - assets/images/prediction.png
    - assets/images/sum.png
    - assets/images/max.png
    - assets/images/min.png
    - assets/images/pairs.png
    - assets/images/straight.png
    - assets/images/full.png
    - assets/images/poker.png
    - assets/images/yahtzee.png
    - assets/images/app_logo.png
    - assets/images/BG.png
    - assets/images/splash_screen.png
  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
  

